// Canopy — Sample Demo Data
// 100 fictional employees across a realistic tech company org structure
// Safe to use publicly — all names, emails, and data are entirely fictional

const SAMPLE_DATA = [
  // C-Suite
  { id: "Morgan Ellis", name: "Morgan Ellis", parentId: null, title: "Chief Executive Officer", department: "Executive", salary: "320000", rating: "5", jobLevel: "C-Level", email: "m.ellis@canopy-demo.com", startDate: "2018-03-01", city: "San Francisco", state: "CA" },
  { id: "Jordan Blake", name: "Jordan Blake", parentId: "Morgan Ellis", title: "Chief Financial Officer", department: "Finance", salary: "285000", rating: "5", jobLevel: "C-Level", email: "j.blake@canopy-demo.com", startDate: "2019-01-15", city: "San Francisco", state: "CA" },
  { id: "Taylor Okonkwo", name: "Taylor Okonkwo", parentId: "Morgan Ellis", title: "Chief Technology Officer", department: "Engineering", salary: "295000", rating: "5", jobLevel: "C-Level", email: "t.okonkwo@canopy-demo.com", startDate: "2018-06-01", city: "San Francisco", state: "CA" },
  { id: "Avery Sandoval", name: "Avery Sandoval", parentId: "Morgan Ellis", title: "Chief People Officer", department: "People", salary: "270000", rating: "4", jobLevel: "C-Level", email: "a.sandoval@canopy-demo.com", startDate: "2020-02-01", city: "San Francisco", state: "CA" },
  { id: "Riley Kaufman", name: "Riley Kaufman", parentId: "Morgan Ellis", title: "Chief Revenue Officer", department: "Sales", salary: "290000", rating: "5", jobLevel: "C-Level", email: "r.kaufman@canopy-demo.com", startDate: "2019-09-01", city: "New York", state: "NY" },
  { id: "Casey Nguyen", name: "Casey Nguyen", parentId: "Morgan Ellis", title: "Chief Marketing Officer", department: "Marketing", salary: "265000", rating: "4", jobLevel: "C-Level", email: "c.nguyen@canopy-demo.com", startDate: "2020-07-01", city: "Austin", state: "TX" },

  // Finance VPs & ICs
  { id: "Quinn Hartley", name: "Quinn Hartley", parentId: "Jordan Blake", title: "VP Financial Planning", department: "Finance", salary: "195000", rating: "4", jobLevel: "VP", email: "q.hartley@canopy-demo.com", startDate: "2019-04-01", city: "San Francisco", state: "CA" },
  { id: "Sloane Mercer", name: "Sloane Mercer", parentId: "Quinn Hartley", title: "Senior Financial Analyst", department: "Finance", salary: "125000", rating: "5", jobLevel: "IC4", email: "s.mercer@canopy-demo.com", startDate: "2020-08-01", city: "San Francisco", state: "CA" },
  { id: "Drew Callahan", name: "Drew Callahan", parentId: "Quinn Hartley", title: "Financial Analyst", department: "Finance", salary: "98000", rating: "4", jobLevel: "IC3", email: "d.callahan@canopy-demo.com", startDate: "2021-03-15", city: "San Francisco", state: "CA" },
  { id: "Reese Yamamoto", name: "Reese Yamamoto", parentId: "Quinn Hartley", title: "Financial Analyst", department: "Finance", salary: "95000", rating: "3", jobLevel: "IC3", email: "r.yamamoto@canopy-demo.com", startDate: "2022-01-10", city: "Remote", state: "OR" },
  { id: "Parker Osei", name: "Parker Osei", parentId: "Jordan Blake", title: "VP Accounting", department: "Finance", salary: "190000", rating: "4", jobLevel: "VP", email: "p.osei@canopy-demo.com", startDate: "2019-11-01", city: "San Francisco", state: "CA" },
  { id: "Emery Johansson", name: "Emery Johansson", parentId: "Parker Osei", title: "Senior Accountant", department: "Finance", salary: "115000", rating: "4", jobLevel: "IC4", email: "e.johansson@canopy-demo.com", startDate: "2020-05-01", city: "San Francisco", state: "CA" },
  { id: "Sage Whitfield", name: "Sage Whitfield", parentId: "Parker Osei", title: "Accountant", department: "Finance", salary: "88000", rating: "3", jobLevel: "IC2", email: "s.whitfield@canopy-demo.com", startDate: "2023-02-01", city: "San Francisco", state: "CA" },

  // Engineering VPs & Teams
  { id: "Rowan Patel", name: "Rowan Patel", parentId: "Taylor Okonkwo", title: "VP Engineering — Platform", department: "Engineering", salary: "210000", rating: "5", jobLevel: "VP", email: "r.patel@canopy-demo.com", startDate: "2018-09-01", city: "San Francisco", state: "CA" },
  { id: "Finley Oduya", name: "Finley Oduya", parentId: "Taylor Okonkwo", title: "VP Engineering — Product", department: "Engineering", salary: "205000", rating: "4", jobLevel: "VP", email: "f.oduya@canopy-demo.com", startDate: "2019-06-01", city: "San Francisco", state: "CA" },
  { id: "Skyler Brennan", name: "Skyler Brennan", parentId: "Taylor Okonkwo", title: "VP Data & AI", department: "Engineering", salary: "215000", rating: "5", jobLevel: "VP", email: "s.brennan@canopy-demo.com", startDate: "2020-01-15", city: "Seattle", state: "WA" },

  // Platform Engineering
  { id: "Asher Kim", name: "Asher Kim", parentId: "Rowan Patel", title: "Engineering Manager — Infrastructure", department: "Engineering", salary: "175000", rating: "4", jobLevel: "M2", email: "a.kim@canopy-demo.com", startDate: "2019-03-01", city: "San Francisco", state: "CA" },
  { id: "Lennon Cruz", name: "Lennon Cruz", parentId: "Asher Kim", title: "Staff Engineer", department: "Engineering", salary: "195000", rating: "5", jobLevel: "IC4", email: "l.cruz@canopy-demo.com", startDate: "2019-07-01", city: "San Francisco", state: "CA" },
  { id: "Harlow Desai", name: "Harlow Desai", parentId: "Asher Kim", title: "Senior Software Engineer", department: "Engineering", salary: "165000", rating: "4", jobLevel: "IC3", email: "h.desai@canopy-demo.com", startDate: "2020-04-01", city: "San Francisco", state: "CA" },
  { id: "Indigo Marsh", name: "Indigo Marsh", parentId: "Asher Kim", title: "Senior Software Engineer", department: "Engineering", salary: "160000", rating: "4", jobLevel: "IC3", email: "i.marsh@canopy-demo.com", startDate: "2020-11-01", city: "Remote", state: "TX" },
  { id: "Bellamy Russo", name: "Bellamy Russo", parentId: "Asher Kim", title: "Software Engineer", department: "Engineering", salary: "135000", rating: "3", jobLevel: "IC2", email: "b.russo@canopy-demo.com", startDate: "2022-03-01", city: "San Francisco", state: "CA" },
  { id: "Zephyr Cohen", name: "Zephyr Cohen", parentId: "Asher Kim", title: "Software Engineer", department: "Engineering", salary: "130000", rating: "2", jobLevel: "IC2", email: "z.cohen@canopy-demo.com", startDate: "2022-08-15", city: "Remote", state: "NY" },

  // Product Engineering
  { id: "Marlowe Singh", name: "Marlowe Singh", parentId: "Finley Oduya", title: "Engineering Manager — Frontend", department: "Engineering", salary: "172000", rating: "4", jobLevel: "M2", email: "m.singh@canopy-demo.com", startDate: "2019-10-01", city: "San Francisco", state: "CA" },
  { id: "Delaney Park", name: "Delaney Park", parentId: "Marlowe Singh", title: "Senior Frontend Engineer", department: "Engineering", salary: "158000", rating: "5", jobLevel: "IC3", email: "d.park@canopy-demo.com", startDate: "2020-02-01", city: "San Francisco", state: "CA" },
  { id: "Caspian Webb", name: "Caspian Webb", parentId: "Marlowe Singh", title: "Frontend Engineer", department: "Engineering", salary: "128000", rating: "4", jobLevel: "IC2", email: "c.webb@canopy-demo.com", startDate: "2021-06-01", city: "Remote", state: "CO" },
  { id: "Soleil Okafor", name: "Soleil Okafor", parentId: "Marlowe Singh", title: "Frontend Engineer", department: "Engineering", salary: "125000", rating: "3", jobLevel: "IC2", email: "s.okafor@canopy-demo.com", startDate: "2022-01-15", city: "Remote", state: "GA" },
  { id: "Cypress Tan", name: "Cypress Tan", parentId: "Finley Oduya", title: "Engineering Manager — Backend", department: "Engineering", salary: "170000", rating: "3", jobLevel: "M1", email: "c.tan@canopy-demo.com", startDate: "2020-05-01", city: "San Francisco", state: "CA" },
  { id: "Wren Adeyemi", name: "Wren Adeyemi", parentId: "Cypress Tan", title: "Senior Backend Engineer", department: "Engineering", salary: "162000", rating: "4", jobLevel: "IC3", email: "w.adeyemi@canopy-demo.com", startDate: "2020-09-01", city: "San Francisco", state: "CA" },
  { id: "Piper Nakamura", name: "Piper Nakamura", parentId: "Cypress Tan", title: "Backend Engineer", department: "Engineering", salary: "132000", rating: "3", jobLevel: "IC2", email: "p.nakamura@canopy-demo.com", startDate: "2021-11-01", city: "Remote", state: "WA" },
  { id: "Hadley Reeves", name: "Hadley Reeves", parentId: "Cypress Tan", title: "Backend Engineer", department: "Engineering", salary: "128000", rating: "2", jobLevel: "IC2", email: "h.reeves@canopy-demo.com", startDate: "2023-03-01", city: "Remote", state: "FL" },

  // Data & AI
  { id: "Reign Blackwood", name: "Reign Blackwood", parentId: "Skyler Brennan", title: "Engineering Manager — ML", department: "Engineering", salary: "180000", rating: "5", jobLevel: "M2", email: "r.blackwood@canopy-demo.com", startDate: "2020-03-01", city: "Seattle", state: "WA" },
  { id: "Sable Ferreira", name: "Sable Ferreira", parentId: "Reign Blackwood", title: "Staff ML Engineer", department: "Engineering", salary: "200000", rating: "5", jobLevel: "IC4", email: "s.ferreira@canopy-demo.com", startDate: "2020-07-01", city: "Seattle", state: "WA" },
  { id: "Orion Lindqvist", name: "Orion Lindqvist", parentId: "Reign Blackwood", title: "Senior ML Engineer", department: "Engineering", salary: "170000", rating: "4", jobLevel: "IC3", email: "o.lindqvist@canopy-demo.com", startDate: "2021-02-01", city: "Remote", state: "MA" },
  { id: "Vesper Anand", name: "Vesper Anand", parentId: "Reign Blackwood", title: "ML Engineer", department: "Engineering", salary: "145000", rating: "4", jobLevel: "IC2", email: "v.anand@canopy-demo.com", startDate: "2022-05-01", city: "Seattle", state: "WA" },
  { id: "Lux Owusu", name: "Lux Owusu", parentId: "Skyler Brennan", title: "Senior Data Analyst", department: "Engineering", salary: "138000", rating: "4", jobLevel: "IC3", email: "l.owusu@canopy-demo.com", startDate: "2021-08-01", city: "Seattle", state: "WA" },
  { id: "Callum Petrov", name: "Callum Petrov", parentId: "Skyler Brennan", title: "Data Analyst", department: "Engineering", salary: "108000", rating: "3", jobLevel: "IC2", email: "c.petrov@canopy-demo.com", startDate: "2023-01-15", city: "Remote", state: "IL" },

  // People (HR)
  { id: "Briar Fontaine", name: "Briar Fontaine", parentId: "Avery Sandoval", title: "VP Talent Acquisition", department: "People", salary: "185000", rating: "4", jobLevel: "VP", email: "b.fontaine@canopy-demo.com", startDate: "2020-04-01", city: "San Francisco", state: "CA" },
  { id: "Cosmo Eze", name: "Cosmo Eze", parentId: "Briar Fontaine", title: "Senior Recruiter", department: "People", salary: "112000", rating: "5", jobLevel: "IC3", email: "c.eze@canopy-demo.com", startDate: "2020-09-01", city: "San Francisco", state: "CA" },
  { id: "Fern Holloway", name: "Fern Holloway", parentId: "Briar Fontaine", title: "Recruiter", department: "People", salary: "88000", rating: "4", jobLevel: "IC2", email: "f.holloway@canopy-demo.com", startDate: "2021-06-15", city: "Remote", state: "NC" },
  { id: "Juno Blackstone", name: "Juno Blackstone", parentId: "Briar Fontaine", title: "Recruiter", department: "People", salary: "85000", rating: "3", jobLevel: "IC2", email: "j.blackstone@canopy-demo.com", startDate: "2022-09-01", city: "Remote", state: "OH" },
  { id: "Moss Eriksen", name: "Moss Eriksen", parentId: "Avery Sandoval", title: "VP People Operations", department: "People", salary: "182000", rating: "4", jobLevel: "VP", email: "m.eriksen@canopy-demo.com", startDate: "2020-08-01", city: "San Francisco", state: "CA" },
  { id: "Rue Castellanos", name: "Rue Castellanos", parentId: "Moss Eriksen", title: "Senior HRBP", department: "People", salary: "118000", rating: "5", jobLevel: "IC3", email: "r.castellanos@canopy-demo.com", startDate: "2021-01-15", city: "San Francisco", state: "CA" },
  { id: "Lark Ogundimu", name: "Lark Ogundimu", parentId: "Moss Eriksen", title: "HRBP", department: "People", salary: "95000", rating: "4", jobLevel: "IC2", email: "l.ogundimu@canopy-demo.com", startDate: "2021-10-01", city: "Remote", state: "TX" },
  { id: "Cleo Mistry", name: "Cleo Mistry", parentId: "Moss Eriksen", title: "People Coordinator", department: "People", salary: "72000", rating: "3", jobLevel: "IC1", email: "c.mistry@canopy-demo.com", startDate: "2023-04-01", city: "San Francisco", state: "CA" },

  // Sales
  { id: "Fox Delacroix", name: "Fox Delacroix", parentId: "Riley Kaufman", title: "VP Enterprise Sales", department: "Sales", salary: "205000", rating: "5", jobLevel: "VP", email: "f.delacroix@canopy-demo.com", startDate: "2019-08-01", city: "New York", state: "NY" },
  { id: "Arlo Mensah", name: "Arlo Mensah", parentId: "Fox Delacroix", title: "Sales Manager — East", department: "Sales", salary: "155000", rating: "4", jobLevel: "M1", email: "a.mensah@canopy-demo.com", startDate: "2020-03-01", city: "New York", state: "NY" },
  { id: "Nova Svensson", name: "Nova Svensson", parentId: "Arlo Mensah", title: "Senior Account Executive", department: "Sales", salary: "138000", rating: "5", jobLevel: "IC3", email: "n.svensson@canopy-demo.com", startDate: "2020-08-15", city: "New York", state: "NY" },
  { id: "Dash Okonkwo", name: "Dash Okonkwo", parentId: "Arlo Mensah", title: "Account Executive", department: "Sales", salary: "115000", rating: "4", jobLevel: "IC2", email: "d.okonkwo@canopy-demo.com", startDate: "2021-04-01", city: "Boston", state: "MA" },
  { id: "Ember Fitzgerald", name: "Ember Fitzgerald", parentId: "Arlo Mensah", title: "Account Executive", department: "Sales", salary: "108000", rating: "3", jobLevel: "IC2", email: "e.fitzgerald@canopy-demo.com", startDate: "2022-02-01", city: "Remote", state: "NJ" },
  { id: "Hawk Leblanc", name: "Hawk Leblanc", parentId: "Fox Delacroix", title: "Sales Manager — West", department: "Sales", salary: "152000", rating: "4", jobLevel: "M1", email: "h.leblanc@canopy-demo.com", startDate: "2020-06-01", city: "Los Angeles", state: "CA" },
  { id: "Juniper Achebe", name: "Juniper Achebe", parentId: "Hawk Leblanc", title: "Senior Account Executive", department: "Sales", salary: "135000", rating: "4", jobLevel: "IC3", email: "j.achebe@canopy-demo.com", startDate: "2021-01-01", city: "Los Angeles", state: "CA" },
  { id: "Birch Volkov", name: "Birch Volkov", parentId: "Hawk Leblanc", title: "Account Executive", department: "Sales", salary: "112000", rating: "3", jobLevel: "IC2", email: "b.volkov@canopy-demo.com", startDate: "2022-07-01", city: "Remote", state: "AZ" },
  { id: "Story Osei", name: "Story Osei", parentId: "Hawk Leblanc", title: "Account Executive", department: "Sales", salary: "108000", rating: "2", jobLevel: "IC2", email: "s.osei@canopy-demo.com", startDate: "2023-01-01", city: "Remote", state: "NV" },
  { id: "Willa Nakagawa", name: "Willa Nakagawa", parentId: "Riley Kaufman", title: "VP Sales Development", department: "Sales", salary: "192000", rating: "4", jobLevel: "VP", email: "w.nakagawa@canopy-demo.com", startDate: "2020-11-01", city: "New York", state: "NY" },
  { id: "Flint Abara", name: "Flint Abara", parentId: "Willa Nakagawa", title: "SDR Manager", department: "Sales", salary: "135000", rating: "4", jobLevel: "M1", email: "fl.abara@canopy-demo.com", startDate: "2021-03-01", city: "New York", state: "NY" },
  { id: "Clover Petersen", name: "Clover Petersen", parentId: "Flint Abara", title: "Senior SDR", department: "Sales", salary: "92000", rating: "5", jobLevel: "IC2", email: "cl.petersen@canopy-demo.com", startDate: "2021-09-01", city: "New York", state: "NY" },
  { id: "Zara Ibáñez", name: "Zara Ibáñez", parentId: "Flint Abara", title: "SDR", department: "Sales", salary: "72000", rating: "4", jobLevel: "IC1", email: "z.ibanez@canopy-demo.com", startDate: "2022-06-01", city: "Remote", state: "TX" },
  { id: "Reed Johansson", name: "Reed Johansson", parentId: "Flint Abara", title: "SDR", department: "Sales", salary: "70000", rating: "3", jobLevel: "IC1", email: "re.johansson@canopy-demo.com", startDate: "2023-02-15", city: "Remote", state: "MN" },

  // Marketing
  { id: "Lyric Dubois", name: "Lyric Dubois", parentId: "Casey Nguyen", title: "VP Brand & Content", department: "Marketing", salary: "188000", rating: "4", jobLevel: "VP", email: "l.dubois@canopy-demo.com", startDate: "2020-09-01", city: "Austin", state: "TX" },
  { id: "Poet Andersen", name: "Poet Andersen", parentId: "Lyric Dubois", title: "Senior Content Strategist", department: "Marketing", salary: "118000", rating: "5", jobLevel: "IC3", email: "p.andersen@canopy-demo.com", startDate: "2021-02-01", city: "Austin", state: "TX" },
  { id: "Raven Okeke", name: "Raven Okeke", parentId: "Lyric Dubois", title: "Content Strategist", department: "Marketing", salary: "92000", rating: "4", jobLevel: "IC2", email: "ra.okeke@canopy-demo.com", startDate: "2021-10-01", city: "Remote", state: "TN" },
  { id: "Fleur Kozlov", name: "Fleur Kozlov", parentId: "Lyric Dubois", title: "Brand Designer", department: "Marketing", salary: "105000", rating: "4", jobLevel: "IC2", email: "fl.kozlov@canopy-demo.com", startDate: "2022-03-15", city: "Austin", state: "TX" },
  { id: "Gale Ochieng", name: "Gale Ochieng", parentId: "Casey Nguyen", title: "VP Growth & Demand Gen", department: "Marketing", salary: "195000", rating: "5", jobLevel: "VP", email: "g.ochieng@canopy-demo.com", startDate: "2020-05-01", city: "Austin", state: "TX" },
  { id: "Blaze Andriessen", name: "Blaze Andriessen", parentId: "Gale Ochieng", title: "Senior Growth Manager", department: "Marketing", salary: "128000", rating: "5", jobLevel: "IC3", email: "bl.andriessen@canopy-demo.com", startDate: "2020-11-01", city: "Austin", state: "TX" },
  { id: "Seren Bakr", name: "Seren Bakr", parentId: "Gale Ochieng", title: "Demand Gen Manager", department: "Marketing", salary: "115000", rating: "4", jobLevel: "IC3", email: "s.bakr@canopy-demo.com", startDate: "2021-07-01", city: "Remote", state: "CO" },
  { id: "Cove Watanabe", name: "Cove Watanabe", parentId: "Gale Ochieng", title: "Marketing Analyst", department: "Marketing", salary: "88000", rating: "3", jobLevel: "IC2", email: "c.watanabe@canopy-demo.com", startDate: "2022-09-01", city: "Remote", state: "WA" },
  { id: "Frost Diallo", name: "Frost Diallo", parentId: "Gale Ochieng", title: "Marketing Coordinator", department: "Marketing", salary: "68000", rating: "3", jobLevel: "IC1", email: "fr.diallo@canopy-demo.com", startDate: "2023-06-01", city: "Remote", state: "GA" },

  // Product Management
  { id: "Halo Brennan", name: "Halo Brennan", parentId: "Taylor Okonkwo", title: "VP Product", department: "Product", salary: "225000", rating: "5", jobLevel: "VP", email: "ha.brennan@canopy-demo.com", startDate: "2019-05-01", city: "San Francisco", state: "CA" },
  { id: "Wilder Otieno", name: "Wilder Otieno", parentId: "Halo Brennan", title: "Director of Product", department: "Product", salary: "185000", rating: "4", jobLevel: "M2", email: "wi.otieno@canopy-demo.com", startDate: "2020-01-01", city: "San Francisco", state: "CA" },
  { id: "Plum Eriksson", name: "Plum Eriksson", parentId: "Wilder Otieno", title: "Senior Product Manager", department: "Product", salary: "162000", rating: "5", jobLevel: "IC4", email: "pl.eriksson@canopy-demo.com", startDate: "2020-06-01", city: "San Francisco", state: "CA" },
  { id: "Levi Oguike", name: "Levi Oguike", parentId: "Wilder Otieno", title: "Product Manager", department: "Product", salary: "138000", rating: "4", jobLevel: "IC3", email: "le.oguike@canopy-demo.com", startDate: "2021-04-01", city: "Remote", state: "NY" },
  { id: "Wisteria Chang", name: "Wisteria Chang", parentId: "Wilder Otieno", title: "Product Manager", department: "Product", salary: "135000", rating: "3", jobLevel: "IC3", email: "wi.chang@canopy-demo.com", startDate: "2021-11-01", city: "Remote", state: "CA" },
  { id: "Atlas Nwosu", name: "Atlas Nwosu", parentId: "Halo Brennan", title: "Senior Product Manager", department: "Product", salary: "158000", rating: "4", jobLevel: "IC4", email: "at.nwosu@canopy-demo.com", startDate: "2020-09-01", city: "San Francisco", state: "CA" },
  { id: "Calla Sørensen", name: "Calla Sørensen", parentId: "Halo Brennan", title: "Product Manager", department: "Product", salary: "132000", rating: "4", jobLevel: "IC3", email: "ca.sorensen@canopy-demo.com", startDate: "2022-02-01", city: "Remote", state: "OR" },

  // Design
  { id: "Bram Oladipo", name: "Bram Oladipo", parentId: "Halo Brennan", title: "VP Design", department: "Design", salary: "210000", rating: "5", jobLevel: "VP", email: "br.oladipo@canopy-demo.com", startDate: "2019-10-01", city: "San Francisco", state: "CA" },
  { id: "Zola Petersen", name: "Zola Petersen", parentId: "Bram Oladipo", title: "Design Manager", department: "Design", salary: "165000", rating: "4", jobLevel: "M1", email: "zo.petersen@canopy-demo.com", startDate: "2020-04-01", city: "San Francisco", state: "CA" },
  { id: "Aura Kowalski", name: "Aura Kowalski", parentId: "Zola Petersen", title: "Senior Product Designer", department: "Design", salary: "148000", rating: "5", jobLevel: "IC3", email: "au.kowalski@canopy-demo.com", startDate: "2020-10-01", city: "San Francisco", state: "CA" },
  { id: "Milo Adekunle", name: "Milo Adekunle", parentId: "Zola Petersen", title: "Product Designer", department: "Design", salary: "118000", rating: "4", jobLevel: "IC2", email: "mi.adekunle@canopy-demo.com", startDate: "2021-08-01", city: "Remote", state: "NY" },
  { id: "Pearl Lindberg", name: "Pearl Lindberg", parentId: "Zola Petersen", title: "Product Designer", department: "Design", salary: "112000", rating: "3", jobLevel: "IC2", email: "pe.lindberg@canopy-demo.com", startDate: "2022-05-01", city: "Remote", state: "CA" },
  { id: "Crest Yamada", name: "Crest Yamada", parentId: "Bram Oladipo", title: "Senior UX Researcher", department: "Design", salary: "138000", rating: "4", jobLevel: "IC3", email: "cr.yamada@canopy-demo.com", startDate: "2021-03-01", city: "San Francisco", state: "CA" },
  { id: "Fable Osei", name: "Fable Osei", parentId: "Bram Oladipo", title: "UX Researcher", department: "Design", salary: "108000", rating: "3", jobLevel: "IC2", email: "fa.osei@canopy-demo.com", startDate: "2022-11-01", city: "Remote", state: "IL" },

  // Customer Success
  { id: "Vale Nkosi", name: "Vale Nkosi", parentId: "Riley Kaufman", title: "VP Customer Success", department: "Customer Success", salary: "198000", rating: "4", jobLevel: "VP", email: "va.nkosi@canopy-demo.com", startDate: "2020-02-01", city: "New York", state: "NY" },
  { id: "Lune Bergström", name: "Lune Bergström", parentId: "Vale Nkosi", title: "CS Manager — Enterprise", department: "Customer Success", salary: "148000", rating: "5", jobLevel: "M1", email: "lu.bergstrom@canopy-demo.com", startDate: "2020-07-01", city: "New York", state: "NY" },
  { id: "Rook Adebayo", name: "Rook Adebayo", parentId: "Lune Bergström", title: "Senior Customer Success Manager", department: "Customer Success", salary: "118000", rating: "5", jobLevel: "IC3", email: "ro.adebayo@canopy-demo.com", startDate: "2021-01-15", city: "New York", state: "NY" },
  { id: "Tide Olofsson", name: "Tide Olofsson", parentId: "Lune Bergström", title: "Customer Success Manager", department: "Customer Success", salary: "95000", rating: "4", jobLevel: "IC2", email: "ti.olofsson@canopy-demo.com", startDate: "2021-09-01", city: "Remote", state: "PA" },
  { id: "Dune Achebe", name: "Dune Achebe", parentId: "Lune Bergström", title: "Customer Success Manager", department: "Customer Success", salary: "92000", rating: "3", jobLevel: "IC2", email: "du.achebe@canopy-demo.com", startDate: "2022-04-01", city: "Remote", state: "VA" },
  { id: "Bay Okonkwo", name: "Bay Okonkwo", parentId: "Vale Nkosi", title: "CS Manager — Mid-Market", department: "Customer Success", salary: "142000", rating: "4", jobLevel: "M1", email: "ba.okonkwo@canopy-demo.com", startDate: "2021-02-01", city: "Chicago", state: "IL" },
  { id: "Gem Thorsen", name: "Gem Thorsen", parentId: "Bay Okonkwo", title: "Customer Success Manager", department: "Customer Success", salary: "90000", rating: "4", jobLevel: "IC2", email: "ge.thorsen@canopy-demo.com", startDate: "2021-10-01", city: "Chicago", state: "IL" },
  { id: "Arc Diallo", name: "Arc Diallo", parentId: "Bay Okonkwo", title: "Customer Success Manager", department: "Customer Success", salary: "88000", rating: "3", jobLevel: "IC2", email: "ar.diallo@canopy-demo.com", startDate: "2022-08-01", city: "Remote", state: "MI" },
  { id: "Loch Ferreira", name: "Loch Ferreira", parentId: "Bay Okonkwo", title: "Customer Onboarding Specialist", department: "Customer Success", salary: "72000", rating: "4", jobLevel: "IC1", email: "lo.ferreira@canopy-demo.com", startDate: "2023-03-15", city: "Remote", state: "MO" },

  // Legal & Ops
  { id: "Cliff Okafor", name: "Cliff Okafor", parentId: "Morgan Ellis", title: "General Counsel", department: "Legal", salary: "275000", rating: "5", jobLevel: "VP", email: "cl.okafor@canopy-demo.com", startDate: "2019-04-01", city: "San Francisco", state: "CA" },
  { id: "Banks Ivanova", name: "Banks Ivanova", parentId: "Cliff Okafor", title: "Senior Corporate Counsel", department: "Legal", salary: "195000", rating: "4", jobLevel: "IC4", email: "ba.ivanova@canopy-demo.com", startDate: "2020-06-01", city: "San Francisco", state: "CA" },
  { id: "Wren Mensah", name: "Wren Mensah", parentId: "Cliff Okafor", title: "Legal Counsel", department: "Legal", salary: "158000", rating: "4", jobLevel: "IC3", email: "wr.mensah@canopy-demo.com", startDate: "2021-05-01", city: "Remote", state: "DC" },
  { id: "Dusk Kowalczyk", name: "Dusk Kowalczyk", parentId: "Morgan Ellis", title: "VP Operations", department: "Operations", salary: "220000", rating: "4", jobLevel: "VP", email: "du.kowalczyk@canopy-demo.com", startDate: "2019-02-01", city: "San Francisco", state: "CA" },
  { id: "Lark Osei", name: "Lark Osei", parentId: "Dusk Kowalczyk", title: "Senior Operations Manager", department: "Operations", salary: "145000", rating: "4", jobLevel: "M1", email: "la.osei@canopy-demo.com", startDate: "2020-01-15", city: "San Francisco", state: "CA" },
  { id: "Fawn Nkosi", name: "Fawn Nkosi", parentId: "Lark Osei", title: "Operations Analyst", department: "Operations", salary: "95000", rating: "4", jobLevel: "IC2", email: "fa.nkosi@canopy-demo.com", startDate: "2021-06-01", city: "San Francisco", state: "CA" },
  { id: "Coda Eriksen", name: "Coda Eriksen", parentId: "Lark Osei", title: "Operations Analyst", department: "Operations", salary: "92000", rating: "3", jobLevel: "IC2", email: "co.eriksen@canopy-demo.com", startDate: "2022-10-01", city: "Remote", state: "AZ" },
];
